import Head from 'next/head';
import Header from "./Header";
import {useDarkMode} from "./useDarkMode";
import Footer from "./Footer";

const Layout = ({ children, title, description }) => {
    const [theme, themeToggler, mountedComponent] = useDarkMode();
    if (!mountedComponent) return <div />

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta property="og:title" content="My page title" key="title" />
                <meta name="description" content="Generated by create next app" />
                <meta content="Daniel Eden, Designer" name="title" />
                <link href="/images/favicon.svg" rel="icon" type="image/svg+xml" />
                <meta name="twitter:title" content="Daniel Eden, Designer"/>
                <meta name="twitter:description" content="Generated by create next app" />
                <meta name="og:description" content="Generated by create next app" />
                <meta content="Generated by create next app" property="og:image" />
                <meta content="Generated by create next app" property="og:image:secure_url" />
                <meta content="Generated by create next app" property="twiiter:image" />
                <meta content="1200" property="og:image:width" />
                <meta content="630" property="og:image:height" />
                <meta content="summary_large_image" name="twitter:card" />
            </Head>
            <main className={theme}>
                <Header theme={theme} toggleTheme={themeToggler} />
                {children}
                <Footer />
            </main>
        </>
    )
}

export default Layout;