import Head from 'next/head'
import Image from 'next/image'
import Header from "./../src/components/Header";
import Grid from "./../styles/Grid.module.scss";
import List from "./../styles/List.module.scss";

export default function Home() {
    return (
        <>
            <div>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main>
                    <Header />
                    <section id="about-section" className={`about-section ${Grid.wrapper}`}>
                        <div className={`${Grid.centered}`}>
                            <h2>Ueno is a full-service agency, busy designing and building beautiful digital products, brands, and experiences.</h2>
                            <div>
                                <p>Well, I’m a designer with 20 years of experience in brand, product design, and creative direction. I have an international reputation for creating warm, smart, and effective design for a variety of companies in technology and publishing. Among these is Abstract, which I co-founded in 2014. I’m currently creative director at Fictive Kin.</p>
                                <p>I also write and speak about design. Several of my essays and lectures are assigned in design classrooms around the world and act as foundational texts in the web design industry, including Everything Easy is Hard Again, The Web’s Grain, and What Screens Want. In 2012, I wrote, illustrated, and published The Shape of Design.</p>
                            </div>
                        </div>
                    </section>
                    <section id="writing-section" className={`writing-section ${Grid.wrapper}`}>
                        <div className={`${Grid.content} ${Grid.centered}`}>
                            <h2>Select Writing</h2>
                            <div>
                                <ul className={List.articles}>
                                    <li><a href="">3 Strategies For Effective Cross-Team Collaboration</a><span>APRIL 6, 2020</span></li>
                                    <li><a>3×3 GTD: A Priority-Driven To Do List</a><span>MAY 26, 2020</span></li>
                                    <li><a>Square Peg, Round Hole: Typed Programming For Designers</a><span>JUNE 6, 2020</span></li>
                                </ul>
                            </div>
                        </div>
                    </section>
                    <section id="experience-section"  className={`experience-section ${Grid.wrapper}`}>
                        <div className={`${Grid.content} ${Grid.centered}`}>
                            <h2>Work Experience</h2>
                            <div>
                                <ul className={List.experience}>
                                    <li>
                                        <div>
                                            <a href="">Software Developer</a>
                                            <span>BIG CABAL MEDIA</span>
                                            <p>Setting creative vision, providing design leadership, establishing process, and managing client relationships, while participating as an IC at a leading digital agency whose clients include Sweetgreen, Ogilvy, National Geographic, TripAdvisor, and Samsung.</p>
                                        </div>
                                        
                                    </li>
                                    <li>
                                        <div>
                                            <a href="">Software Developer</a>
                                            <span>NOTJUSTOK INC</span>
                                            <p>Design and consulting for early stage startups and established leaders at the intersection of brand and digital product. Clients included: Etsy, Meetup, Kaplan, Abstract, and many YC startups.</p>
                                        </div>
                                    </li>
                                    <li>
                                        <div>
                                            <a href="">Full-stack Web Developer</a>
                                            <span>VENTRA MEDIA GROUP</span>
                                            <p>The traditional set of founder responsibilities: setting vision, creating product definition, fundraising, and company leadership. Lead design across brand and product, and helped define the company’s go-to-market approach.</p>
                                        </div>
                                    </li>
                                    <li>
                                        <a href="">Front-end Developer</a>
                                        <span>CKDIGITAL</span>
                                        <p>Product design, web design, publication design, branding, and illustration. Clients include: Nike, Microsoft, NPR, Adobe, Facebook, WIRED, Bloomberg Businessweek, O’Reilly Media, The Atlantic, and Justin Bieber (sorta).</p>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </section>
                </main>
            </div>
            <style jsx>{`
                .about-section,
                .writing-section,
                .experience-section {
                    padding: var(--sp-xxxl) 0;
                }

                .writing-section {
                    background-color: #fafafa;
                }

                .about-section h2 {
                    width: 80%;
                    font-size: 40px;
                    font-weight: 500;
                    color: var(--black);
                    line-height: 1.2;
                }

                p {
                    margin-top: 0;
                }

                main {
                    padding-bottom: var(--sp-xxl);
                }

                h2 {
                    color: #777777;
                }
                
                h2 em {
                    display: block;
                    color: #8d8f9a;
                }
            `}</style>
        </>
    )
}
