import Head from 'next/head'
import Image from 'next/image'
import Header from "./../src/components/Header";
import Grid from "./../styles/Grid.module.scss";

export default function Home() {
    return (
        <>
            <div>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main>
                    <Header />
                    <div className={Grid.wrapper}>
                        <div id="about" className={Grid.content}>
                            <h2>About me?</h2>
                            <div>
                                Well, I’m a designer with 20 years of experience in brand, product design, and creative direction. I have an international reputation for creating warm, smart, and effective design for a variety of companies in technology and publishing. Among these is Abstract, which I co-founded in 2014. I’m currently creative director at Fictive Kin.
                            </div>
                        </div>
                        <div id="select-writing" className={Grid.content}>
                            <h2>Select Writing</h2>
                            <div>
                                Well, I’m a designer with 20 years of experience in brand, product design, and creative direction. I have an international reputation for creating warm, smart, and effective design for a variety of companies in technology and publishing. Among these is Abstract, which I co-founded in 2014. I’m currently creative director at Fictive Kin.
                            </div>
                        </div>
                    </div>
                </main>
            </div>
            <style jsx>{`
                header {
                    
                }
            `}</style>
        </>
    )
}
