import Head from 'next/head'
import Image from 'next/image'
import Header from "./../src/components/Header";
import Footer from "./../src/components/Footer"
import Grid from "./../styles/Grid.module.scss";
import List from "./../styles/List.module.scss";
import Photo from "./../public/images/face.jpeg";

export default function Home() {
    return (
        <>
            <div>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main>
                    <Header />
                    <section id="writing-section" className={`writing-section ${Grid.wrapper}`}>
                        <div className={`${Grid.centered}`}>
                            <Image src={Photo} />
                            <div>
                                <p>Daniel Eden is a Design Manager at Facebook in London, supporting Facebook’s Commerce organisation. He spends his time writing, thinking, tweeting, and talking about Design Systems: how they scale, how they break, and the people that maintain them.</p>
                                <p className="push-right">
                                    <a href="">Read more <span className="link-emoji">↓</span></a>
                                </p>
                            </div>
                        </div>
                    </section>
                    <section id="writing-section" className={`writing-section ${Grid.wrapper}`}>
                        <div className={`${Grid.centered}`}>
                            <h2>Select Writing</h2>
                            <div>
                                <ul className={List.articles}>
                                    <li><a href="">3 Strategies For Effective Cross-Team Collaboration</a><span>APRIL 6, 2020</span></li>
                                    <li><a>3×3 GTD: A Priority-Driven To Do List</a><span>MAY 26, 2020</span></li>
                                    <li><a>Square Peg, Round Hole: Typed Programming For Designers</a><span>JUNE 6, 2020</span></li>
                                </ul>
                            </div>
                        </div>
                    </section>
                    <Footer />
                </main>
            </div>
            <style jsx>{`
                .writing-section {
                    padding: var(--sp-xl) 0;
                }

                p {
                    font-family: var(--font-body);
                    font-weight: 400;
                    line-height: 1.4;
                }

                .push-right {
                    text-align: right;
                    font-size: 16px;
                    text-transform: capitalize;
                    font-weight: 700;
                }

                .push-right a {
                    display: inline-block;
                    transition: color .2s, transform .2s;
                }

                .push-right a:hover {
                    transform: translate(5px);
                    color: var(--text-color-hover);
                }

                span.link-emoji {
                    transform: rotate(-90deg);
                    display: inline-block;
                }

                h2 {
                    font-family: var(--font-body);
                    font-size: 32px
                    line-height: 0.95;
                    font-weight: 500;
                }

                h2 em {
                    font-weight: 100;
                }
            `}</style>
        </>
    )
}
